<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PcUsageTracker.Core\PcUsageTracker.Core.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.15" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>PcUsageTracker.Infrastructure</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

</Project>